name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        version: [6, 8, 10, 12, 14, 16]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - run: yarn import
      - run: yarn install --check-files
      # - run: npm ci
      - run: yarn build
      - run: yarn units